### ISSUE TITLE
[2.x] How to initialize with Typescript?

### ISSUE THREAD

**Issue by dirkluijk** [timruffles/ios-html5-drag-drop-shim#104]
The polyfill is not working with Typescript, when I import it:

```
import "drag-drop-polyfill";
```

``DragDropPolyfill`` is not defined. I expected something like ``import {DragDropPolyfill} from "drag-drop-polyfill";`` or ``import * as DragDropPolyfill from "drag-drop-polyfill";`` but that doesn't work either.

I guess the object is not exported correctly. 

I am using 2.0.0-beta.3.

**Comment by reppners** [comment]
Sorry for the inconvenience, this is fixed already but not yet released since the 2.0 release including a rename is pending. I'll wrap up a `rc.0` release to make it easily usable.

You can try this workaround meanwhile:
https://github.com/timruffles/ios-html5-drag-drop-shim/issues/83#issuecomment-278627280

**Comment by reppners** [comment]
Just published `drag-drop-polyfill@2.0.0-rc.0` which can be imported with
`import {polyfill} from "drag-drop-polyfill/drag-drop-polyfill";`

A top level index files which re-exports the polyfill and addons might be contained in the final release.

Let me know if this fixes your problem.

**Comment by dirkluijk** [comment]
Thank you. This fixed the issue. Got some other issues now, that I didn't have in 1.x, but I 'll have another look at that.
