### ISSUE TITLE
Support other mobile browsers

### ISSUE THREAD

**Issue by jmeas** [timruffles/ios-html5-drag-drop-shim#40]
By adding a few more checks to the [`userAgent` check](https://github.com/timruffles/ios-html5-drag-drop-shim/blob/master/ios-drag-drop.js#L16), we can determine if the user is using Android, and make this library more general.

@xStrom [suggested that this works over in production on his app](https://github.com/timruffles/ios-html5-drag-drop-shim/issues/30#issuecomment-91062703), and I'm doing a similar hack myself.

Question:

A similar method can be used to add support for Blackberry and Windows Phone. Do we want to do that?

//cc @xStrom @timruffles

**Comment by xStrom** [comment]
Ideally we would only use feature detection. We do have feature detection in there, but iOS Safari (and apparently also the Android browser) report that they support drag events while in reality they do not. That's why we have the additional user-agent checks. Modernizr has the same feature detection as us, which also fails. [Other people have come to the same solution.](http://stackoverflow.com/a/6221626/138826)

Regarding support of minority platforms, I don't think we should prevent code from working on them due to some "not supported" policy. However I personally do not have any way to test on them and thus would rather not commit to proper support for those platforms.

So the question for me becomes, is the code currently not executing? Do the browsers on these platforms also lie about their drag events and thus give a false positive to our feature detection?

Also of note is that the [Windows Phone 8.1 user-agent](https://msdn.microsoft.com/en-us/library/ie/hh869301(v=vs.85).aspx) is:
```Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537```

Thus it already gets patched by the iPhone detection. Older Windows Phone browsers don't have that, but do they have proper touch events? Do they lie about drag events? I don't really know. I guess we could also add ```IEMobile``` for the hell of it.

**Comment by xStrom** [comment]
By the way, [your own hack](https://github.com/jmeas/ios-html5-drag-drop-shim/blob/master/ios-drag-drop.js#L16) is probably broken on browsers that support both touch events and drag events, like desktop Chrome.
