### ISSUE TITLE
Unexpected behaviour on Nexus 7

### ISSUE THREAD

**Issue by derwaldgeist** [timruffles/ios-html5-drag-drop-shim#50]
This shim causes a quite weird behaviour on Nexus 7 devices (running stock Android Lollipop). If you add the shim to your page, _all_ images become automatically draggable (even if the "draggable" attribute has not been set on them) - and all other events on these images are prevented. In effect, you can now drag nearly every image, but you cannot interact with them anymore (e.g. if you use them as buttons)...

**Comment by xStrom** [comment]
All images are draggable even without the shim, at least on desktop browsers. We do have problems with sending click events to draggable elements though, as discussed in #23. We have a short-term hack in place for anchor elements and this could potentially be extended to cover images as well. I'll look into it. Speaking long-term, we have a major rewrite underway which should handle these scenarios closer to the way that desktop browsers do.

Now, you said that *all other events on these images are prevented*. I'm curious, what other events besides click are you having trouble with?

**Comment by derwaldgeist** [comment]
Thanks for answering that quick. If I remove the shim, the images are not draggable. They only become draggable once I include the shim. So the shim is causing this behaviour.

By *all other events* I meant click events in particular, I haven't tried others so far.

**Comment by xStrom** [comment]
The shim is causing the behavior indeed. That's the whole point of the shim, isn't it? The mobile browsers don't have drag-n-drop support, so this shim adds that functionality. Some elements, like `<a/>` & `<img/>` have the `draggable` attribute `true` by default, even on the mobile browsers. So images being draggable is the correct & expected behavior. If you don't want this, you have to explicitly set the `draggable` attribute to `false` on those images.

The images not receiving a click event when you just press on them is a bug however, which I'll attempt to solve.

**Comment by derwaldgeist** [comment]
Ah ok, I see. Did not know that draggable images are the default if draggable support is enabled.
