### ISSUE TITLE
Drop target always set to document.body

### ISSUE THREAD

**Issue by evasomething** [timruffles/ios-html5-drag-drop-shim#73]
I'd like for drop target to be set to _immediateUserSelection and was wondering if any of these
steps are still supported?

https://github.com/timruffles/ios-html5-drag-drop-shim/blob/rewrite/src/drag-drop-polyfill.ts#L749

**Comment by reppners** [comment]
As far as dropzone attribute support is concerned I do not have any plans to implement them because they are not implemented by browsers that support native drag and drop.

To achieve the desired effect just implement drag and drop as usual by canceling the `dragenter`-event on the desired drop target element.

**Comment by evasomething** [comment]
Thanks for the response! If I understand correctly, the idea is that dropping will be allowed on on the target element if default dragenter behavior is cancelled on it, right?

I'm trying this though and It seems that the dragexit, dragleave, dragover, and drop events are firing at document.body and the event listeners on my target aren't picking up on the event.. was wondering if maybe I'm missing something?

**Comment by evasomething** [comment]
oops nevermind, that seems to have done the trick, thanks for the help!
